//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichTodd.QuiltSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichTodd.QuiltSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;$SUBJECT$&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .email-body {
        ///            font-family: Verdana, Geneva, Tahoma, sans-serif;
        ///            font-size: 12pt;
        ///            width: 100%;
        ///            height: 100%;
        ///            background-color: #fbf3b7;
        ///        }
        ///
        ///        .email-content {
        ///            width: 600px;
        ///            margin: 20px;
        ///            padding: 20px;
        ///            background-color: #ffffff;
        ///        }
        ///
        ///        .email-header {
        ///            text-align: cente [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailHtmlTemplate {
            get {
                return ResourceManager.GetString("EmailHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    From: $SENDER-NAME$ ($SENDER-EMAIL$)
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Subject: $MESSAGE-SUBJECT$
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    $MESSAGE-TEXT$
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Click &lt;a href=&quot;$ADMIN-FULL-URL$/Message/Index/%MESSAGE-ID%&quot;&gt;here&lt;/a&gt; to open.
        ///&lt;/p&gt;
        ///$ORDER-COMPONENT$.
        /// </summary>
        internal static string EmailInboundMessageHtmlTemplate {
            get {
                return ResourceManager.GetString("EmailInboundMessageHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    &lt;a href=&quot;$ADMIN-FULL-URL$/Order/Index/$ORDER-ID$&quot;&gt;Order $ORDER-NUMBER$&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string EmailInboundMessageOrderHtmlComponent {
            get {
                return ResourceManager.GetString("EmailInboundMessageOrderHtmlComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Order $ORDER-NUMBER$: $ADMIN-FULL-URL$/Order/Index/$ORDER-ID$.
        /// </summary>
        internal static string EmailInboundMessageOrderTextComponent {
            get {
                return ResourceManager.GetString("EmailInboundMessageOrderTextComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: $SENDER-NAME$ ($SENDER-EMAIL$)
        ///Subject: $MESSAGE-SUBJECT$
        ///
        ///$MESSAGE-TEXT$
        ///
        ///Open message: $ADMIN-FULL-URL$/Message/Index/%MESSAGE-ID%
        ///
        ///$ORDER-COMPONENT$.
        /// </summary>
        internal static string EmailInboundMessageTextTemplate {
            get {
                return ResourceManager.GetString("EmailInboundMessageTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Subject: $MESSAGE-SUBJECT$
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    $MESSAGE-TEXT$
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Click &lt;a href=&quot;$FULL-URL$/Message/Index/%MESSAGE-ID%&quot;&gt;here&lt;/a&gt; to open.
        ///&lt;/p&gt;
        ///$ORDER-COMPONENT$.
        /// </summary>
        internal static string EmailOutboundMessageHtmlTemplate {
            get {
                return ResourceManager.GetString("EmailOutboundMessageHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    &lt;a href=&quot;$FULL-URL$/Order/Index/$ORDER-ID$&quot;&gt;Order $ORDER-NUMBER$&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string EmailOutboundMessageOrderHtmlComponent {
            get {
                return ResourceManager.GetString("EmailOutboundMessageOrderHtmlComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Order $ORDER-NUMBER$: $FULL-URL$/Order/Index/$ORDER-ID$.
        /// </summary>
        internal static string EmailOutboundMessageOrderTextComponent {
            get {
                return ResourceManager.GetString("EmailOutboundMessageOrderTextComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject: $MESSAGE-SUBJECT$
        ///
        ///$MESSAGE-TEXT$
        ///
        ///Open message: $FULL-URL$/Message/Index/%MESSAGE-ID%
        ///
        ///$ORDER-COMPONENT$.
        /// </summary>
        internal static string EmailOutboundMessageTextTemplate {
            get {
                return ResourceManager.GetString("EmailOutboundMessageTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $SUBJECT$
        ///
        ///$TEMPLATE-BODY$.
        /// </summary>
        internal static string EmailTextTemplate {
            get {
                return ResourceManager.GetString("EmailTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    A new account was created at &lt;a href=&quot;$FULL-URL$&quot;&gt;$URL$&lt;/a&gt; using this email address.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    If you created this account, please confirm by clicking &lt;a href=&quot;$LINK$&quot;&gt;here&lt;/a&gt;.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Alternatively, you may copy and paste the following URL into a browser window:
        ///&lt;/p&gt;
        ///&lt;pre class=&quot;email-prewrap&quot;&gt;$LINK$&lt;/pre&gt;
        ///&lt;p&gt;
        ///    If you did not register this e-mail address, please delete this e-mail.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    For questions about this e-mail, please contact &lt;a href=&quot;mailto:$SUPPORT-EMAIL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailUserRegistrationHtmlTemplate {
            get {
                return ResourceManager.GetString("EmailUserRegistrationHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new account was created at $URL$ using this email address.
        ///
        ///If you created this account, please confirm by clicking the following link.
        ///
        ///$LINK$
        ///
        ///Alternatively, you may copy and paste the link into a browser window.
        ///
        ///If you did not register this e-mail address, please delete this e-mail.
        ///
        ///For questions about this e-mail, please contact $SUPPORT-EMAIL$..
        /// </summary>
        internal static string EmailUserRegistrationTextTemplate {
            get {
                return ResourceManager.GetString("EmailUserRegistrationTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    A password reset request was made at &lt;a href=&quot;$FULL-URL$&quot;&gt;$URL$&lt;/a&gt; using this email address.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    If you made this request, please confirm by clicking &lt;a href=&quot;$LINK$&quot;&gt;here&lt;/a&gt;.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Alternatively, you may copy and paste the following URL into a browser window:
        ///&lt;/p&gt;
        ///&lt;pre class=&quot;email-prewrap&quot;&gt;$LINK$&lt;/pre&gt;
        ///&lt;p&gt;
        ///    If you did not make this request, please delete this e-mail.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    For questions about this e-mail, please contact &lt;a href=&quot;mailto:$SUPPORT-EMAIL$&quot;&gt;$SU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailUserResetHtmlTemplate {
            get {
                return ResourceManager.GetString("EmailUserResetHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset request was made at $URL$ using this email address.
        ///
        ///If you created this account, please confirm by clicking the following link.
        ///
        ///$LINK$
        ///
        ///Alternatively, you may copy and paste the link into a browser window.
        ///
        ///If you did make this request, please delete this e-mail.
        ///
        ///For questions about this e-mail, please contact $SUPPORT-EMAIL$..
        /// </summary>
        internal static string EmailUserResetTextTemplate {
            get {
                return ResourceManager.GetString("EmailUserResetTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE view [dbo].[FulfillableToShipmentRequestView] as
        ///select distinct
        ///	FI.FulfillableId,
        ///	SRI.ShipmentRequestId
        ///from
        ///	FulfillableItem FI inner join
        ///	ShipmentRequestItem SRI on SRI.FulfillableItemId = FI.FulfillableItemId;
        ///GO
        ///CREATE view [dbo].[ShipmentRequestSummaryView] as
        ///select 
        ///	SR.ShipmentRequestId,
        ///	SR.ShipmentRequestNumber,
        ///	SR.ShipmentRequestStatusCode,
        ///	SR.ShipmentRequestStatusDateTimeUtc,
        ///	SR.CreateDateTimeUtc,
        ///	F.FulfillableId,
        ///	F.Name as FulfillableName,
        ///	F.FulfillableReferenc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelCreateViews {
            get {
                return ResourceManager.GetString("ModelCreateViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your recent order at $URL$ has shipped.
        ///
        ///You can view this order and tracking information using the following link:
        ///
        ///    %ORDER%
        ///
        ///We appreciate your business.
        ///
        ///$WEBSITE-NAME$
        ///
        ///This email was sent from a notification-only address that cannot accept incoming email. Please do not reply to this message..
        /// </summary>
        internal static string OrderShippedNotification {
            get {
                return ResourceManager.GetString("OrderShippedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your recent order at $URL$ is being prepared for shipment.  We will send you another notification when the order has been shipped.
        ///
        ///You can view this order using the following link:
        ///
        ///    %ORDER%
        ///
        ///We appreciate your business.
        ///
        ///$WEBSITE-NAME$
        ///
        ///This email was sent from a notification-only address that cannot accept incoming email. Please do not reply to this message..
        /// </summary>
        internal static string OrderShippingNotification {
            get {
                return ResourceManager.GetString("OrderShippingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A refund has been issued for your order at $URL$.
        ///
        ///You can view this order using the following link:
        ///
        ///    %ORDER%
        ///
        ///We appreciate your business.
        ///
        ///$WEBSITE-NAME$
        ///
        ///This email was sent from a notification-only address that cannot accept incoming email. Please do not reply to this message..
        /// </summary>
        internal static string RefundIssuedNotification {
            get {
                return ResourceManager.GetString("RefundIssuedNotification", resourceCulture);
            }
        }
    }
}
